crud_app/urls.py
from django.conf.urls import url
from .views import *
app_name="crud_app"
urlpatterns = [
    url(r'^$',home,name="home"),
    url(r'^update/(?P<pk>\w+)/$', update,name="update"),
    url(r'^delete/(?P<pk>\w+)/$',delete,name="delete"),
    url(r'add/',addd,name="addd"),

]

crud_with_django_mongo/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('crud_app.urls')),
]

crud_app/models.py
from djongo import models


class EmployeeData(models.Model):
	name=models.CharField(max_length=20,unique=True)
	date=models.DateTimeField(auto_now_add=True)
	def __str__(self):
		return self.name

crud_app/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import EmployeeData
def home(request):
	data=EmployeeData.objects.all()
	return render(request,'index.html',{'data':data})
	
def addd(request):
	
	if request.method=="POST":
		data=EmployeeData(name=request.POST['name'])
		data.save()
		return redirect("crud_app:home")
		
	else:
			
		return render(request,'add.html')
	

	
def update(request,pk):
	data=EmployeeData.objects.get(name=pk)
	if request.method=="POST":
		n=request.POST['name']
		print (n)
		data.name=n
		data.save()
		return redirect('crud_app:home')
	else: 
		
		return render(request,'update.html',{'data':data})
def delete(request,pk):
	data=EmployeeData.objects.get(name=pk)
	data.delete()
	return redirect('crud_app:home')
	

templates/add.html
{% extends 'base.html'%}

{%block content%}
<h1 align="center">Add page</h1>
<hr>
<p align="center"><a href="{%url 'crud_app:home'%}">Home</a></p>
<form action="" method="POST">
{%csrf_token%}
<input type="text" name="name">
<input type="submit" value="submit">
</form>
{%endblock%}

templates/base.html
<!DOCTYPE html>
<html>
<head>
</head>
<style>
body{
background:black;
color:white;
}
a{
color:white;
cursor:pointer;
}
table, th, td {
  border: 1px solid white;
}
</style>
<body>

{%block content%}

{%endblock%}
</body>
</html>

templates/index.html
{% extends 'base.html'%}

{%block content%}
<h1 align="center">Home page</h1>
<hr>
<p align="center"><a href="{%url 'crud_app:addd'%}">Add Data</a></p>
 <table style="width:100%">
  <tr>
    <th>Name</th>
    <th>Update</th>
    <th>Delete</th>
  </tr>
{%for data in data%}
  <tr>
    <td>{{data.name}}</td>
    <td><a href="update/{{data.name}}"><button>Update</button></a></td></td>
    <td><a href="delete/{{data.name}}"><button>Delete</button></a></td></td>
  </tr>
{%endfor%}
  </table> 


{%endblock%}

templates/update.html
{% extends 'base.html'%}

{%block content%}
<h1>Update page</h1>
<form action="/update/{{data.name}}/" method="POST">
{%csrf_token%}
<input type="text" name=name value={{data.name}}>
<input type="submit" value="submit">
</form>
{%endblock%}